name: Build
on:
  workflow_call:
    inputs:
      branch-postfix:
        required: false
        type: string
env:
  BUILD: ${{ inputs.branch-postfix == 'master' && 'Release' || 'Debug' }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Increment Version
        uses: action-pack/increment@v2
        with:
          name: "VERSION"
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build Executables
        shell: pwsh
        run: |
          $env:GITHUB_RUN_ID = $null
          dotnet publish --nologo -c $env:BUILD -r win-x64 --version-suffix test /p:Version=1.0.${{ vars.VERSION }}
          dotnet publish --nologo -c $env:BUILD -r win-x86 --version-suffix test /p:Version=1.0.${{ vars.VERSION }}
          dotnet publish --nologo -c $env:BUILD -r osx-x64 --version-suffix test /p:Version=1.0.${{ vars.VERSION }}
          dotnet publish --nologo -c $env:BUILD -r linux-x64 --version-suffix test /p:Version=1.0.${{ vars.VERSION }}
          $artifactPath = Join-Path (Get-Location) 'artifacts'
          if (!(Test-Path $artifactPath))
          {
              New-Item $artifactPath -ItemType Directory -Force
          }
          $startPath = Join-Path (Get-Location) 'src' 'bin' $env:BUILD 'net8.0'
          Copy-Item (Join-Path $startPath 'win-x64' 'publish' 'Oxide.Compiler.exe') (Join-Path $artifactPath 'win-x64.Compiler.exe') -Force
          Copy-Item (Join-Path $startPath 'win-x86' 'publish' 'Oxide.Compiler.exe') (Join-Path $artifactPath 'win-x86.Compiler.exe') -Force
          Copy-Item (Join-Path $startPath 'linux-x64' 'publish' 'Oxide.Compiler') (Join-Path $artifactPath 'linux-x64.Compiler') -Force
          Copy-Item (Join-Path $startPath 'osx-x64' 'publish' 'Oxide.Compiler') (Join-Path $artifactPath 'osx-x64.Compiler') -Force
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: artifacts/
